unit-test for nodelogs collector.
Azure/aks-periscope pull request #109
Opened 2021-09-02 21:24 UTC by Tatsinnit

Unit test the node logs collector.

2021-09-06 11:41 UTC, arnaud-tincelin approved these changes
If this works for both AKS & Kind clusters you may merge

2021-09-06 20:59 UTC, Tatsinnit commented
> If this works for both AKS & Kind clusters you may merge

Sounds good 👍 , I will cc: @sophsoph321 as well. for a quick test for quick `arc` scenarios test, test image is : `docker.io/tatsat/node-logs-unittest` - I have tested against `AKS` and kind is part of test.

Thanks,

2021-09-07 17:53 UTC, sophsoph321 requested changes
Thanks @Tatsinnit for sharing the private image and for making these changes. I tested these changes with a kind cluster and received the following errors: 
1. For DNS collector: **collect data failed: open /run/systemd/resolve/resolv.conf: no such file or directory** 
2. For node logs collector: collect data failed: open /var/log/azure/cluster-provision.log: no such file or directory

2021-09-07 18:09 UTC, Tatsinnit commented
> Thanks @Tatsinnit for sharing the private image and for making these changes. I tested these changes with a kind cluster and received the following errors:
> 
> 1. For DNS collector: **collect data failed: open /run/systemd/resolve/resolv.conf: no such file or directory**
> 2. For node logs collector: collect data failed: open /var/log/azure/cluster-provision.log: no such file or directory

Thanks @sophsoph321 , did you specifically used the yaml file I shared with you? Because that file will resolve this other. Thanks 🙏

2021-09-07 18:20 UTC, Tatsinnit commented
> Thanks @Tatsinnit for sharing the private image and for making these changes. I tested these changes with a kind cluster and received the following errors:
> 
> 1. For DNS collector: **collect data failed: open /run/systemd/resolve/resolv.conf: no such file or directory**
> 2. For node logs collector: collect data failed: open /var/log/azure/cluster-provision.log: no such file or directory

Thank you @sophsoph321 ,

When you get a chance can you try this: 

Kubectl get pods - n aks-periscope 

Above will give you pods which are running on your kind cluster context and then take on pod name and run this 

kubectl -n aks-periscope exec -it aks-periscope-h7gml -- /bin/bash

thanks

2021-09-07 23:03 UTC, sophsoph321 approved these changes
Tested on kind cluster and changes look good.

2021-09-08 10:24 UTC, merged

2021-09-09 00:30 UTC, Tatsinnit commented
💡For future reference: Thanks for discussions to @sophsoph321 and @arnaud-tincelin, regarding testing the within cluster test scenarios: 

Arnaud made some good ideas and he is POC-ing soon, Nice thing about is that we can run interactive-pods (https://medium.com/@pczarkowski/kubernetes-tip-run-an-interactive-pod-d701766a12) is that we will have a busy box (https://www.busybox.net) 

Within CI-Pipeline:  (We could do something like this, and fetch the `codecover` file )

* `kubectl run test --image busybox-with-periscope-code --comand [go test -v -race -coverprofile=coverage.out -covermode=atomic ./...]`
* `kubectl cp`

The reason we've removed the one of the new test was because it was not running inside the node as the current unit test run against the cluster. ☕️ Above discussed Idea will unlock that and help improving the overall quality.

Thanks heaps, 🙏❤️